// spell-checker:disable
export const wordCorrections = {
    'metry': 'merry',
    'youa': 'you a',
    'anda': 'and a',
    'Anda': 'And a',
    'andZ': 'and Z',
    'ona': 'on a',
    'ina': 'in a',
    'Ohher': 'Oh her',
    'onlly': 'only',
    'inthe': 'in the',
    'witha': 'with a',
    'meta': 'met a',
    'onmy': 'on my',
    'Ano': 'A no',
    'onher': 'on her',
    'oldman': 'old man',
    'alittle': 'a little',
    'alot': 'a lot',
    'adream': 'a dream',
    'yourABC': 'your ABC',
    'alove': 'a love',

    'Il': 'I',
    '|have': 'I have',
    'Iran': 'I ran',
    'lsee': 'I see',
    'lam': 'I am',
    'lbe': 'I be',
    'Ilose': 'I lose',
    'llove': 'I love',
    'lleaned': 'I leaned',
    'lwasn\'t': 'I wasn\'t',
    'I-I-l-l': 'I I I I',
    'I-I-I-l': 'I I I I',
    'Pye': 'I\'ve',
    'P\'m': 'I\'m',
    'Pm': 'I\'m',
    'Pil': 'I\'ll',
    'Pll': 'I\'ll',
    'lll': 'I\'ll',
    'Ill': 'I\'ll',
    'il': 'I\'ll',
    'Ive': 'I\'ve',
    'I\'min': 'I\'m in',
    'lm': 'I\'m',
    'Ohl': 'Oh I',
    'Whenl': 'When I',
    'Nol': 'No I',
    'YOu': 'YOU',
    'IDO': 'I DO',
    'L..': 'I..',
    'L.,': 'I..',
    'm,': 'm..',
    'l': 'I',
    'Id': 'I\'d',
    'Ifyou': 'If you',
    'youseea': 'you see a',
    'AW': 'Ah',
    'AR': 'Ah',
    '‘Well': 'Well',
    '‘You': 'You',
    'yourre': 'you\'re',

    '@eeeOne,': '**** One,',
    'eeeeI': '**** I',
    'eeeel': '**** I',
    'eeeelI': '**** I',
    '*eee!': '**** I',
    '@¢¢¢Do': '**** Do',
    '@@¢e¢Up': '**** Up',
    'e@eeeRidea': '**** Ride a',
    'e@eeed': '**** A',
    'eeeedld': '**** Old',
    'y>eoelfl': '**** If',
    '*eeeThe': '**** The',
    'eeeeI\'mMnota': '**** I\'m not a',

    'ecee': '****',
    '@¢@¢e¢': '****',
    '*#eee': '****',
    'ete': '****',
    'eee': '****',
    'eee]': '****',
    
    'eeee': '****',
    '@@¢e': '****',
    '«eee': '****',
    '«eel': '****',
    'eee]': '****',
    '*ee*e': '****',
    'seeeceeeeeeeseeeees': '*******************',
    '**': '* *',

    'y>eoelfl': '>>>> If',
    '>>': '> >',
    'yyy': '>>>>',
    '>rrPr': '>>>>',
    '»rr>': '>>>>',
    '>rrP': '>>>>',
    'rrPr': '>>>>',
    'rr': '>>',
    '>r': '>>',
    'Fr>': '>>',
    'yy>': '>>>',
    '>rrr': '>>>>',
    '»rrr': '>>>>',
    '>FPrPr': '>>>>',
    '»FPrPr': '>>>>',
    '>rPrP': '>>>>',
    '»rPrP': '>>>>',

    'onacold': 'on a cold',
    'Satinacorner': 'Sat in a corner',
    'tome,': 'to me,',
    'tome': 'to me', 
    'Tweedie': 'Tweedle',
    'Dat': 'Pat',
    'Lhit': 'I hit',
    'acake': 'a cake',
    'markit': 'mark it',
    'withB': 'with B',

    'ji..ive': 'jive',
    'ji...ive': 'jive',
    'li...i...ife': 'life',
    'Hm...mm,': 'Hmmm',
    'cha...a...ance': 'chance',
    'yea...ea...eah': 'yeah',

    'go-oh': 'go',
    'go-oh,': 'go,',
    'lo-o-ong': 'long',
    'contro-o-ol': 'control',
    'say-ay': 'say',
    'say-ay,': 'say,',
    'play-ay': 'play',
    'play-ay,': 'play,',
    'kno-ow': 'know',
    'know-ow': 'know',
    'do-on’t': 'don\'t',

    'fi...ine': 'fine',
    'ho...o...0...ome': 'home',
    'Hathaway...ay': 'Hathaway',
    'no...ho': 'no',
    'baby...y...y...': 'baby',
    'nea...ear,': 'near',
    'a...a...and': 'and',
    're...est': 'rest',
    'ooh...ooh': 'ooh ooh',
    'o0': 'oo',
    '00': 'oo',
    '0n': 'On',
    'o...on': 'on',
    'me...end': 'mend',
    'drie...ied': 'dried',

    'Wellitsa': 'Well it\'s a',
    'Whenl': 'When I',
    'QOoh': 'Oooh',
    'lwon\'t': 'I won\'t',
    'Onasilent': 'On a silent',
    'aromantic': 'a romantic',
    'ascummy': 'a scummy',
    'ascumbag': 'a scumbag',
    'atrifle': 'a trifle',
    'Andl\'ve': 'And I\'ve',
    'seenhim': 'seen him',
    'lil': 'I\'ll',
    'f---ing': 'f-ing',
    'TT': '-',

    'forge...e...et': 'forget',
    
    '(Female Singer)': '',
    '(Male Singer)': '',
    '(Female': '',
    '(Male': '',
    'Singer)': '',

    'Lo...ove,': 'Love,',
    'Lo...ove': 'Love',
    'lo...ove': 'love',
    'lo...ove,': 'love',
    'No...no...no,': 'no no no',
    'Qh-ooh-oh-oh': 'Oh-ooh-oh-oh',
    '0': 'o',

    'Oti,': 'OT,',
    'oti,': 'OT,',
    'oti': 'OT',
    'iL.ign': 'i.ign',
    'solcan': 'so I can',
    'Pillet': 'I\'ll let',
    'canrest': 'can rest',
    'Burm': 'Burn',
    'moming': 'morning',
    'moreis': 'more is',
    'theyin': 'they in',
    'aworser': 'a worser',
    'Outin': 'Out in',
    'moreis': 'more is',
    'Thisisa': 'This is a',
    'sucha': 'such a',
    'lcan': 'I can',
    'arest,': 'a rest,',
    
};


// Letters and substrings
export const letterCorrections = {
    '’': '\'',
    '‘': '\'',
    '“': '\'',
    '”': '\'',
    '"': '\'',
    '—': '-',
    '®': '*',
    '<': '(',
    '»': '>',
    '«': '*',
    '®': '*',
    '@': '*',
    '¢': '*',
    '#': '*',
    '|': 'I',
    'Qh': 'Oh',
    'Qoh': 'Ooh',
    'o0h': 'ooh',
};
// spell-checker:enable


