// spell-checker:disable
export const wordCorrections = {
    'metry': 'merry',
    'youa': 'you a',
    'anda': 'and a',
    'Anda': 'And a',
    'andZ': 'and Z',
    'ona': 'on a',
    'ina': 'in a',
    'witha': 'with a',
    'meta': 'met a',
    'onmy': 'on my',
    'onher': 'on her',
    'oldman': 'old man',
    'alittle': 'a little',
    'adream': 'a dream',
    'yourABC': 'your ABC',
    'Il': 'I',
    '|have': 'I have',
    'Iran': 'I ran',
    'lsee': 'I see',
    'Pye': 'I\'ve',
    'P\'m': 'I\'m',
    'Pm': 'I\'m',
    'Pil': 'I\'ll',
    'lll': 'I\'ll',
    'Ill': 'I\'ll',
    'il': 'I\'ll',
    'Ive': 'I\'ve',
    'I\'min': 'I\'m in',
    'YOu': 'YOU',
    'IDO': 'I DO',
    'Ifyou': 'If you',
    'youseea': 'you see a',
    '‘Well': 'Well',
    '‘You': 'You',
    '@eeeOne,': '**** One,',
    '@¢¢¢Do': '**** Do',
    '@@¢e¢Up': '**** Up',
    'e@eeeRidea': '**** Ride a',
    'e@eeed': '**** A',
    'eeeedld': '**** Old',
    '@¢@¢e¢': '****',
    'ete': '****',
    'eee': '****',
    'eeee': '****',
    '@@¢e': '****',
    'seeeceeeeeeeseeeees': '*******************',
    '**': '* *',
    '>>': '> >',
    'yyy': '>>>>',
    '»rr>': '>>>>',
    'rr': '>>',

    'onacold': 'on a cold',
    'Satinacorner': 'Sat in a corner',
    'tome,': 'to me,',
    'tome': 'to me', 
    'Tweedie': 'Tweedle',
    'Dat': 'Pat',
    'Lhit': 'I hit',
    'acake': 'a cake',
    'markit': 'mark it',
    'withB': 'with B',

    'ji..ive': 'jive',
    'ji...ive': 'jive',
    'li...i...ife': 'life',
    'Hm...mm,': 'Hmmm',
    'cha...a...ance': 'chance',
    'yea...ea...eah': 'yeah',

    'go-oh': 'go',
    'go-oh,': 'go,',
    'lo-o-ong': 'long',
    'contro-o-ol': 'control',
    'say-ay': 'say',
    'say-ay,': 'say,',
    'play-ay': 'play',
    'play-ay,': 'play,',
    'kno-ow': 'know',
    'know-ow': 'know',
    'do-on’t': 'don\'t',

    'fi...ine': 'fine',
    'ho...o...0...ome': 'home',
    'Hathaway...ay': 'Hathaway',
    'no...ho': 'no',
    'baby...y...y...': 'baby',
    'nea...ear,': 'near',
    'a...a...and': 'and',
    're...est': 'rest',
    'ooh...ooh': 'ooh ooh',
    'o...on': 'on',
    'me...end': 'mend',
    'drie...ied': 'dried',

    'ascummy': 'a scummy',
    'ascumbag': 'a scumbag',
    'Andl\'ve': 'And I\'ve',
    'seenhim': 'seen him',
    'lil': 'I\'ll',
    'f---ing': 'f-ing',
    'TT': '-',

    'forge...e...et': 'forget',
    
    '(Female Singer)': '',
    '(Male Singer)': '',

    'Lo...ove': 'love',
    'lo...ove': 'love',
    'lo...ove,': 'love',
    'No...no...no,': 'no no no',
    
};


// Letters and substrings
export const letterCorrections = {
    '’': '\'',
    '‘': '\'',
    '“': '\'',
    '”': '\'',
    '®': '*',
    '»': '>',
    '®': '*',
    '@': '*',
    '¢': '*',
    '|': 'I',
    'Qoh': 'Ooh',
    'o0h': 'ooh',
};
// spell-checker:enable


