// spell-checker:disable
export const corrections = {
    'metry': 'merry',
    'youa': 'you a',
    'anda': 'and a',
    'Anda': 'And a',
    'andZ': 'and Z',
    'ona': 'on a',
    'ina': 'in a',
    'witha': 'with a',
    'meta': 'met a',
    'onmy': 'on my',
    'onher': 'on her',
    'oldman': 'old man',
    'alittle': 'a little',
    'adream': 'a dream',
    'yourABC': 'your ABC',
    '|': 'I',
    '|have': 'I have',
    '»»»»': '>>>>',
    'YOu': 'YOU',
    'IDO': 'I DO',
    'won’t': 'won\'t',
    'wasn’t': 'wasn\'t',
    '‘Well': 'Well',
    '‘You': 'You',
    '@eeeOne,': '**** One,',
    '@¢¢¢Do': '**** Do',
    'e@eeed': '**** A',
    'eeeedld': '**** Old',
    '@@¢e¢Up': '**** Up',
    'e@eeeRidea': '**** Ride a',
    '®': '*',
    '**®': '***',
    'ete': '****',
    '***®': '****',
    '@@¢e': '****',
    '@¢@¢¢': '****',
    '@@¢¢': '****',
    '@¢@¢e¢': '****',
    'onacold': 'on a cold',
    'Satinacorner': 'Sat in a corner',
    'tome,': 'to me,',
    'tome': 'to me', 
    'Tweedie': 'Tweedle',
    'Dat': 'Pat',
    'acake': 'a cake',
    'markit': 'mark it',
    'withB': 'with B',
};
// spell-checker:enable
